<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:07:52.
 */
class notificaComponentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var notificaComponent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new notificaComponent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers notificaComponent::format_notificacao_notifica_url
     * @todo   Implement testFormat_notificacao_notifica_url().
     */
    public function testFormat_notificacao_notifica_url() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers notificaComponent::ajaxCheck
     * @todo   Implement testAjaxCheck().
     */
    public function testAjaxCheck() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
