<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:07:51.
 */
class notificacao_notificaModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var notificacao_notificaModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new notificacao_notificaModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers notificacao_notificaModel::paginate
     * @todo   Implement testPaginate().
     */
    public function testPaginate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers notificacao_notificaModel::getPaginationCount
     * @todo   Implement testGetPaginationCount().
     */
    public function testGetPaginationCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers notificacao_notificaModel::setAllRead
     * @todo   Implement testSetAllRead().
     */
    public function testSetAllRead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers notificacao_notificaModel::setRead
     * @todo   Implement testSetRead().
     */
    public function testSetRead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers notificacao_notificaModel::setUnRead
     * @todo   Implement testSetUnRead().
     */
    public function testSetUnRead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers notificacao_notificaModel::alertar
     * @todo   Implement testAlertar().
     */
    public function testAlertar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers notificacao_notificaModel::apagar
     * @todo   Implement testApagar().
     */
    public function testApagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers notificacao_notificaModel::unstall
     * @todo   Implement testUnstall().
     */
    public function testUnstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
